// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkmlvpjjpzglnkliauiz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rbWx2cGpqcHpnbG5rbGlhdWl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3ODg5MjksImV4cCI6MjA1OTM2NDkyOX0.VObux3xFgHcKZJH_FQLm2naxwKeov1P-5_KGimCY8uA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);